/**
 * Produces a deterministic JSON string by sorting object keys RECURSIVELY.
 *
 * Plain `JSON.stringify` preserves property insertion order, so two
 * semantically identical bodies ({a,b} vs {b,a} — e.g. re-serialized by a
 * proxy, built by a different client, or generated by an LLM) hash to
 * different fingerprints and a legitimate retry is rejected as a mismatch
 * (422). Canonicalization makes the fingerprint order-insensitive at EVERY
 * nesting level.
 *
 * NOTE: the replacer-array trick (`JSON.stringify(body, Object.keys(body).sort())`)
 * is NOT a substitute — a replacer array is an allow-list of property names,
 * so nested keys absent from the top level are silently DROPPED from the
 * output (different bodies would fingerprint identically).
 */
export function canonicalStringify(value: unknown): string {
  if (value === null || value === undefined) {
    return 'null';
  }

  // Functions and symbols are not serializable (matches JSON.stringify)
  if (typeof value === 'function' || typeof value === 'symbol') {
    return 'null';
  }

  if (typeof value !== 'object') {
    // BigInt throws in JSON.stringify; render as a string defensively
    if (typeof value === 'bigint') {
      return String(value);
    }
    return JSON.stringify(value);
  }

  // Arrays: order is significant, preserve it
  if (Array.isArray(value)) {
    return '[' + value.map((item) => (item === undefined || typeof item === 'function' || typeof item === 'symbol' ? 'null' : canonicalStringify(item))).join(',') + ']';
  }

  if (value instanceof Date) {
    return JSON.stringify(value);
  }

  // Plain objects: sort keys, skip undefined/function/symbol values
  // (matches JSON.stringify semantics for objects)
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  const parts: string[] = [];
  for (const key of keys) {
    const v = obj[key];
    if (v === undefined || typeof v === 'function' || typeof v === 'symbol') {
      continue;
    }
    parts.push(JSON.stringify(key) + ':' + canonicalStringify(v));
  }
  return '{' + parts.join(',') + '}';
}
